steps:
  # Dump the MongoDB data to an archive
  - name: 'mongo:6.0.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mongodump --host="$MONGO_HOST" \
                  --username="$MONGO_USER" \
                  --password="$MONGO_PASS" \
                  --authenticationDatabase=admin \
                  --archive=/workspace/mongodump.gz

  # Upload the archive to your GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp /workspace/mongodump.gz gs://"$BUCKET"/mongodump-"$(date +'%Y-%m-%d_%H%M')".gz

timeout: "1200s"
