name: Deploy Tasky Webapp to GKE

on:
  push:
    paths:
      - 'k8s/webapp.yaml'
      - '.github/workflows/deploy-webapp.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        id: gke
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: wiz-cluster
          location: us-west1
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      - name: Set variables
        run: |
          echo "PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV

          DB_IP=$(gcloud compute instances describe wiz-db \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --zone="us-west1-a" \
            --format="get(networkInterfaces[0].networkIP)")
          echo "DB_INTERNAL_IP=${DB_IP}" >> $GITHUB_ENV

      - name: Deploy to GKE
        run: |
          # Substitute env vars in the manifest and apply
          envsubst < k8s/webapp.yaml | kubectl apply -f -
