name: Deploy Tasky Webapp to GKE

on:
  push:
    paths:
      - 'k8s/webapp.yaml'
      - '.github/workflows/deploy-webapp.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        id: gke
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: wiz-cluster
          location: us-west1
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Terraform
        run: |
          curl -Lo tf.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
          unzip tf.zip
          sudo mv terraform /usr/local/bin/

      - name: Set variables
        run: |
          echo "PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          DB_IP="$(terraform -chdir=terraform output -raw db_vm_internal_ip)"
          echo "DB_INTERNAL_IP=${DB_IP}" >> $GITHUB_ENV

      - name: Deploy to GKE
        run: |
          # Substitute env vars in the manifest and apply
          envsubst < k8s/webapp.yaml | kubectl apply -f -
