name: Terraform Apply to GCP

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-apply.yml'
  workflow_dispatch:

env:
  TF_WORKING_DIR: 'terraform'
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_region: us-west1
  TF_VAR_zone: us-west1-a

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Import existing resources
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          set +e
          echo "Importing VPC..."
          terraform import module.network.google_compute_network.vpc \
            projects/${{ env.TF_VAR_project_id }}/global/networks/wiz-vpc || true

          echo "Importing Subnet..."
          terraform import module.network.google_compute_subnetwork.subnet \
            projects/${{ env.TF_VAR_project_id }}/regions/${{ env.TF_VAR_region }}/subnetworks/wiz-vpc-subnet || true

          echo "Importing GKE Cluster..."
          terraform import module.gke.google_container_cluster.primary \
            projects/${{ env.TF_VAR_project_id }}/locations/${{ env.TF_VAR_region }}/clusters/wiz-cluster || true

          echo "Importing GKE Node Pool..."
          terraform import module.gke.google_container_node_pool.default \
            projects/${{ env.TF_VAR_project_id }}/locations/${{ env.TF_VAR_region }}/clusters/wiz-cluster/nodePools/wiz-cluster-pool || true

          echo "Importing DB VM..."
          terraform import module.db.google_compute_instance.db_vm \
            projects/${{ env.TF_VAR_project_id }}/zones/${{ env.TF_VAR_zone }}/instances/wiz-db || true

          echo "Importing DB SSH Firewall..."
          terraform import module.db.google_compute_firewall.db_ssh \
            projects/${{ env.TF_VAR_project_id }}/global/firewalls/wiz-db-ssh-ingress || true

          echo "Importing DB Mongo Firewall..."
          terraform import module.db.google_compute_firewall.db_mongo \
            projects/${{ env.TF_VAR_project_id }}/global/firewalls/wiz-db-mongo-ingress || true
          set -e

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=plan.tfplan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve plan.tfplan
